name: Build Multiarch Unbound Docker Image
               
on:
  push:
    branches: [ main ]
             
env:
  DOCKERHUB_SLUG: "madnuttah/unbound"
  VERSION: "1.17.1-2"
  REVISION: "2"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@rc
        with:
          egress-policy: block
          allowed-endpoints: 
            dl-cdn.alpinelinux.org:443
            github.com:443
            docker.io
            index.docker.io
            ghcr.io
            auth.docker.io:443
            registry-1.docker.io:443
            production.cloudflare.docker.com:443
            objects.githubusercontent.com:443
            www.nlnetlabs.nl:443
            www.internic.net:443
            keys.openpgp.org:443
            pipelines.actions.githubusercontent.com:443 
    
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
     
      - name: Login to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/386,linux/arm/v6,linux/arm/v7,linux/arm64,linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          file: ./unbound/Dockerfile   
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKERHUB_SLUG }}:${{ env.VERSION }}      
            ${{ env.DOCKERHUB_SLUG }}:latest
      - run: sudo iptables -L -v -n 
